### ISSUE TITLE
White text invisible when editing

### ISSUE THREAD

**Issue by wturnbull** [CuBoulder/ucb_bootstrap_layouts#29]
When going to layout and editing a block with white text, the text does not appear. https://live-ucbdev-sandbox-wendy.pantheonsite.io/node/3/layout 

<img width="1716" alt="Screenshot 2024-04-05 at 10 34 22 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/1757082/d1f7fcdc-00d3-442f-b956-b805f69200bb">
<img width="1657" alt="Screenshot 2024-04-05 at 10 34 38 AM" src="https://github.com/CuBoulder/tiamat-theme/assets/1757082/4245de39-2c0c-4163-b86a-5a1fb992cfc0">

Would expect to be able to see the white text when trying to edit a block, but the white text is still white when editing on a white background and can't see it.

**Comment by jcsparks** [comment]
Duplicate issue : CuBoulder/ucb_bootstrap_layouts#25
