### ISSUE TITLE
Section content frame background colors/options

### ISSUE THREAD

**Issue by kevincrafts** [CuBoulder/ucb_bootstrap_layouts#34]
Can we rename the two current options for content frame color to be: 

- Semitransparent White
- Semitransparent Black

And add additional White and Black options that would have no transparency?

**Semitransparent White**
<img width="1491" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/b348213e-f2c7-4084-a1f0-735792e716fa">

**White**
<img width="1487" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/98c13223-de60-42e3-af09-cd50d58015dd">

**Semitransparent Black**
<img width="1488" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/eba3dad0-dfb6-4933-a899-2ed2a93f5100">

**Black**
<img width="1488" alt="image" src="https://github.com/CuBoulder/tiamat-theme/assets/349713/bdc2f083-efcf-42f4-8312-fca5e43847a2">

**Comment by timurtripp** [comment]
@jnicholCU Flagging as a good one to discuss using CSS variables or doing a minor refactor (depending on how much effort you determine is involved).
